### ISSUE TITLE
Макет на Figma vs Movie.kt (Homework #5)

### ISSUE THREAD

**Issue by avanlex** [Android-Academy-Global/fundamentals-2020-homework#5]
В макете на Figma нет поля соответствующего `val adult: Boolean`, как минимум это должна быть `Int`, чтобы соответствовало макету "13+", "16+"  и называться как-то по-другому

Так же не понятно где поле "reviews" c макета

**Comment by emartynov** [comment]
@avanlex подправил. Подтверди, что теперь все есть.

**Comment by avanlex** [comment]
Да, всё гуд😎
